### ISSUE TITLE
Y channel training error with "--n_colors=1"

### ISSUE THREAD

**Issue by KindleHe** [yulunzhang/RCAN#11]
Hi, I am trying to train DIV2K with Y channel using the following scripts, but get some error. First I convert `DIV2K_train_HR` and `DIV2K_train_LR_bicubic ` from rgb to y channel, and rename `DIV2K` to `DIV2K_y`, correspondingly delete `+ '/DIV2K'` in `div2k.py` to keep the training path is right. 
```
CUDA_VISIBLE_DEVICES=1 python3 main.py --n_GPUs 1 --dir_data /root/dataset/super-resolution/DIV2K_y --model RCAN --save RCAN_BIX2_G10R20P48 --scale 2 --n_resgroups 10 --n_resblocks 20 --n_feats 64  --reset --chop --save_results --print_model --patch_size 96 --n_colors=1 --batch_size=48 --n_threads=8 >&1 | tee $LOG
```
Then, I set `--n_colors=1 `, but the error comming:
```
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    t.train()
  File "/root/kindlehe/project/pytorch/RCAN-master/RCAN_TrainCode/code/trainer.py", line 45, in train
    for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train):
  File "/usr/local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/root/kindlehe/project/pytorch/RCAN-master/RCAN_TrainCode/code/dataloader.py", line 47, in _ms_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/root/kindlehe/project/pytorch/RCAN-master/RCAN_TrainCode/code/dataloader.py", line 47, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/root/kindlehe/project/pytorch/RCAN-master/RCAN_TrainCode/code/data/srdata.py", line 90, in __getitem__
    lr, hr = self._get_patch(lr, hr)
  File "/root/kindlehe/project/pytorch/RCAN-master/RCAN_TrainCode/code/data/srdata.py", line 126, in _get_patch
    lr, hr, patch_size, scale, multi_scale=multi_scale
  File "/root/kindlehe/project/pytorch/RCAN-master/RCAN_TrainCode/code/data/common.py", line 23, in get_patch
    img_tar = img_tar[ty:ty + tp, tx:tx + tp, :]
IndexError: too many indices for array
```

**Comment by yulunzhang** [comment]
For single channel, try to modify RCAN_TrainCode/code/data/common.py
Change
img_in   = img_in[iy:iy + ip, ix:ix + ip, :]
img_tar = img_tar[ty:ty + ip, tx:itx + tp, :]
to
img_in   = img_in[iy:iy + ip, ix:ix + ip]
img_tar = img_tar[ty:ty + ip, tx:itx + tp]
