### ISSUE TITLE
test with own images

### ISSUE THREAD

**Issue by meroluo** [yulunzhang/RCAN#37]
Thank you for your wonderful work ! 
Recently I have trained a model with my own datasets, but when I test it ,there seems to be something wrong I can't understand. The error is described as below:

(base) luomeilu@Ubuntu:~/CNN/RCAN-master/RCAN-master/RCAN_TestCode/code$ python main.py --data_test MyImage --scale 4 --model RCAN --n_resgroups 10 --n_resblocks 20 --n_feats 64 --pre_train ../model/RCAN_BIX4.pt --test_only --save_results --chop --save 'RCAN' --testpath ../LR/LRBI --testset Set5
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from option import args
  File "/home/luomeilu/CNN/RCAN-master/RCAN-master/RCAN_TestCode/code/option.py", line 19, in <module>
    help='random seed')
  File "/home/luomeilu/anaconda3/lib/python3.6/argparse.py", line 1338, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'defaut'

Hope you can give me some suggestions, thanks a lot！

**Comment by yulunzhang** [comment]
Hi,
Have you run the original test pipeline with my released model? It should work fine. Then, you can try and test your trained model. And it should also work, because you only changed the dataset.

So, I guess maybe the running environment (you're using the 'base' environment) hasn't been configured for the code.

**Comment by qingchuanhuajuan** [comment]
Hello! Great job and thank you for sharing!
I am not very skilled with pytorch. I want to draw a picture, like Figure 4（Convergence analysis of RDN with different values of D, C, and G.） in your paper（RDN）, where should I change the code?

**Comment by yulunzhang** [comment]
Hi
You don't have to revise the code at all. You can collect all the log files (e.g., log.txt) for different settings. Then you can use matlab/python to extract PSNR values w.r.t. epochs from the log files and plot curves. You can put all these curves into one figure. That's what I did in the RDN paper.
