### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by Jasas9754** [yulunzhang/RCAN#4]
```
[Epoch 3]       Learning rate: 1.00e-4
[1200/12000]    [L1: 7.5750]    141.7+3.7s
[2400/12000]    [L1: 7.6471]    142.1+0.0s
[3600/12000]    [L1: 7.6028]    142.2+0.0s
[4800/12000]    [L1: 7.6049]    145.2+0.0s
[6000/12000]    [L1: 616.0927]  143.3+0.0s
Skip this batch 510! (Loss: 11261144.0)
THCudaCheck FAIL file=c:\programdata\miniconda3\conda-bld\pytorch_1524543037166\work\aten\src\thc\generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    t.train()
  File "C:\Users\motor\RCAN-master\RCAN_TrainCode\code\trainer.py", line 51, in train
    sr = self.model(lr, idx_scale)
  File "C:\Users\motor\Anaconda3\envs\TENSORFLOW\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\motor\RCAN-master\RCAN_TrainCode\code\model\__init__.py", line 54, in forward
    return self.model(x)
  File "C:\Users\motor\Anaconda3\envs\TENSORFLOW\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\motor\RCAN-master\RCAN_TrainCode\code\model\rcan.py", line 110, in forward
    res = self.body(x)
  File "C:\Users\motor\Anaconda3\envs\TENSORFLOW\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\motor\Anaconda3\envs\TENSORFLOW\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "C:\Users\motor\Anaconda3\envs\TENSORFLOW\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\motor\RCAN-master\RCAN_TrainCode\code\model\rcan.py", line 62, in forward
    res = self.body(x)
  File "C:\Users\motor\Anaconda3\envs\TENSORFLOW\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\motor\Anaconda3\envs\TENSORFLOW\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "C:\Users\motor\Anaconda3\envs\TENSORFLOW\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\motor\RCAN-master\RCAN_TrainCode\code\model\rcan.py", line 44, in forward
    res = self.body(x)
  File "C:\Users\motor\Anaconda3\envs\TENSORFLOW\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\motor\Anaconda3\envs\TENSORFLOW\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "C:\Users\motor\Anaconda3\envs\TENSORFLOW\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\motor\RCAN-master\RCAN_TrainCode\code\model\rcan.py", line 25, in forward
    return x * y
RuntimeError: cuda runtime error (2) : out of memory at c:\programdata\miniconda3\conda-bld\pytorch_1524543037166\work\aten\src\thc\generic/THCStorage.cu:58
```
command: python main.py --model RCAN --save RCAN_BDX2_G10R20P48 --scale 2 --n_resgroups 10 --n_resblocks 20 --n_feats 64 --reset --chop --save_results --print_model --patch_size 96  --dir_data  (my dir)--pre_train ../experiment/RCAN_BDX2_G10R20P48/model/model_latest.pt --ext sep --batch_size 12

Environment: WIN 10 GTX1060 6gb ANACONDA3 Python 3.6 Pytorch 4.0 and LR *.npy from jpg for jpeg artifact reduction training

Issues: Because of the problem with VRAM, I reduced the --batch_size to 12(even 8) . However, after a certain amount of training(3 to 10 epoch), I get an error saying that I don't have enough memory. Don't you have this problem in a Linux environment? 

Thank you!

**Comment by Jasas9754** [comment]
That's cool! Thank you.
