### ISSUE TITLE
about resume trainning

### ISSUE THREAD

**Issue by sxd0071** [yulunzhang/RCAN#40]
Hi，sorry to bother you. I have some problems about the Resuming training. Firstly, My training stopped unexpectedly with a setence of 'EOFError: Ran out of input'. I don't know why. Secondly, I want to resume training. I try the setting' --load RCAN_BIX2_G10R20P48 --resume -1 --n_GPUs 2' ,  i got an error as the followings show:

Preparing loss function:
1.000 * L1
Traceback (most recent call last):
  File "/home/img/Desktop/sxd/RCAN/RCAN_TrainCode/code/main.py", line 16, in <module>
    loss = loss.Loss(args, checkpoint) if not args.test_only else None
  File "/home/img/Desktop/sxd/RCAN/RCAN_TrainCode/code/loss/__init__.py", line 67, in __init__
    if args.load != '.': self.load(ckp.dir, cpu=args.cpu)
  File "/home/img/Desktop/sxd/RCAN/RCAN_TrainCode/code/loss/__init__.py", line 140, in load
    for l in self.loss_module:
TypeError: 'DataParallel' object is not iterable

Process finished with exit code 1

**Comment by yulunzhang** [comment]
Hi,
The bug has been fixed. Please update RCAN/RCAN_TrainCode/code/loss/__init__.py
Thanks @MaFuyan
