### ISSUE TITLE
training error with my own dataset

### ISSUE THREAD

**Issue by bberry17** [yulunzhang/RCAN#70]
Hi, I tried to train the model with my images.

but the error code shows up like this :
Preparing loss function:
1.000 * L1
[Epoch 1]	Learning rate: 1.00e-4
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    t.train()
  File "/home/ssai-gpu-a-u/SR/RCAN/RCAN_TrainCode/code/trainer.py", line 45, in train
    for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train):
  File "/home/ssai-gpu-a-u/anaconda3/envs/pt_cu80/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/ssai-gpu-a-u/anaconda3/envs/pt_cu80/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/ssai-gpu-a-u/SR/RCAN/RCAN_TrainCode/code/dataloader.py", line 47, in _ms_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ssai-gpu-a-u/SR/RCAN/RCAN_TrainCode/code/dataloader.py", line 47, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ssai-gpu-a-u/SR/RCAN/RCAN_TrainCode/code/data/srdata.py", line 90, in __getitem__
    lr, hr = self._get_patch(lr, hr)
  File "/home/ssai-gpu-a-u/SR/RCAN/RCAN_TrainCode/code/data/srdata.py", line 128, in _get_patch
    lr, hr = common.augment([lr, hr])
  File "/home/ssai-gpu-a-u/SR/RCAN/RCAN_TrainCode/code/data/common.py", line 81, in augment
    return [_augment(_l) for _l in l]
  File "/home/ssai-gpu-a-u/SR/RCAN/RCAN_TrainCode/code/data/common.py", line 81, in <listcomp>
    return [_augment(_l) for _l in l]
  File "/home/ssai-gpu-a-u/SR/RCAN/RCAN_TrainCode/code/data/common.py", line 76, in _augment
    **if vflip: img = img[::-1, :, :]
IndexError: too many indices for array**

I think there is a problem during data augmentation process and the code you wrote in common.py is like below.: 
  
![image](https://user-images.githubusercontent.com/45968511/61632756-95e8a800-acc8-11e9-86de-aa51dd1fa16f.png)

What should I do to solve this problem? 
My image data sets consist of various resolution images like 275 x 183 ~ 1920 x 1080 with RGB channels. 

Thanks.

**Comment by bberry17** [comment]
I just resize my dataset to bigger, then the problem was solved.
