### ISSUE TITLE
Pytorch loading problem

### ISSUE THREAD

**Issue by greatwallet** [yulunzhang/RCAN#88]
# Error
When trying to run the `TestRCAN_scripts.sh`, here comes the error
```
$ sh TestRCAN_scripts.sh
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "/home/chxt/script/RCAN/RCAN_TestCode/code/data/__init__.py", line 3, in <module>
    from dataloader import MSDataLoader
  File "/home/chxt/script/RCAN/RCAN_TestCode/code/dataloader.py", line 10, in <module>
    from torch._C import _set_worker_signal_handlers, _update_worker_pids, \
ImportError: cannot import name '_update_worker_pids'
```

# System
* Ubuntu 16.04 LTS
* CUDA Version: 10.1
* NVIDIA-SMI 430.40; Driver Version: 430.40
* Python: 3.6.9
* Pytorch 1.3.1
* Conda packages:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
blas                      1.0                         mkl    defaults
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.10.16                    0    defaults
cairo                     1.16.0            h18b612c_1001    conda-forge
certifi                   2019.9.11                py36_0    defaults
cffi                      1.13.2           py36h2e261b9_0    defaults
cloudpickle               1.2.2                      py_0    defaults
cudatoolkit               10.1.243             h6bb024c_0    defaults
cycler                    0.10.0                   py36_0    defaults
cytoolz                   0.10.1           py36h7b6447c_0    defaults
dask-core                 2.8.0                      py_0    defaults
dbus                      1.13.12              h746ee38_0    defaults
decorator                 4.4.1                      py_0    defaults
expat                     2.2.6                he6710b0_0    defaults
ffmpeg                    4.1.3                h167e202_0    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.9.1                h8a8886c_1    defaults
giflib                    5.1.9                h516909a_0    conda-forge
glib                      2.63.1               h5a9c865_0    defaults
gmp                       6.1.2             hf484d3e_1000    conda-forge
gnutls                    3.6.5             hd3a4fd2_1002    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
harfbuzz                  2.4.0                h37c48d4_1    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
icu                       58.2                 h9c2bf20_1    defaults
imageio                   2.6.1                    py36_0    defaults
intel-openmp              2019.4                      243    defaults
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.1.0            py36he6710b0_0    defaults
lame                      3.100             h14c3975_1001    conda-forge
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
liblapacke                3.8.0                    14_mkl    conda-forge
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_0    defaults
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                h576950b_1    conda-forge
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                hea5a465_1    defaults
matplotlib                3.1.1            py36h5429711_0    defaults
mkl                       2019.4                      243    defaults
mkl-service               2.3.0            py36he904b0f_0    defaults
mkl_fft                   1.0.15           py36ha843d7b_0    defaults
mkl_random                1.1.0            py36hd6b4f25_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
nettle                    3.4.1             h1bed415_1002    conda-forge
networkx                  2.4                        py_0    defaults
ninja                     1.9.0            py36hfd86e86_0    defaults
numpy                     1.17.3           py36hd14ec0e_0    defaults
numpy-base                1.17.3           py36hde5b4d6_0    defaults
olefile                   0.46                     py36_0    defaults
opencv                    3.4.7            py36h8949d38_2    conda-forge
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openssl                   1.1.1d               h7b6447c_3    defaults
pcre                      8.43                 he6710b0_0    defaults
pillow                    6.2.1            py36h34e0f95_0    defaults
pip                       19.3.1                   py36_0    defaults
pixman                    0.38.0            h516909a_1003    conda-forge
pycparser                 2.19                     py36_0    defaults
pyparsing                 2.4.5                      py_0    defaults
pyqt                      5.9.2            py36h05f1152_2    defaults
python                    3.6.9                h265db76_0    defaults
python-dateutil           2.8.1                      py_0    defaults
pytorch                   1.3.1           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
pytz                      2019.3                     py_0    defaults
pywavelets                1.1.1            py36h7b6447c_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
readline                  7.0                  h7b6447c_5    defaults
scikit-image              0.15.0           py36he6710b0_0    defaults
scipy                     1.3.1            py36h7c811a0_0    defaults
setuptools                41.6.0                   py36_0    defaults
sip                       4.19.8           py36hf484d3e_0    defaults
six                       1.13.0                   py36_0    defaults
sqlite                    3.30.1               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
toolz                     0.10.0                     py_0    defaults
torchvision               0.4.2                py36_cu101    pytorch
tornado                   6.0.3            py36h7b6447c_0    defaults
tqdm                      4.38.0                     py_0    defaults
wheel                     0.33.6                   py36_0    defaults
x264                      1!152.20180806       h14c3975_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults
```

I suppose maybe the code is not supportive Pytorch 1.3.0 and above.

Could you give me a hint about how to fix this?

**Comment by ZamSul** [comment]
Pytorch 1.3.1 is giving this error "ImportError: cannot import name '_update_worker_pids"
Pytorch 0.4.0 (as recommended by author) is giving error "AttributeError: module 'torch.nn' has no attribute 'ModuleDict"
While Pytorch 0.4.1 is giving this output:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    loader = data.Data(args)
  File "/content/gdrive/My Drive/RCAN/RCAN_TestCode/code/data/__init__.py", line 40, in __init__
    module_test = import_module('data.' +  args.data_test.lower())
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/gdrive/My Drive/RCAN/RCAN_TestCode/code/data/myimage.py", line 7, in <module>
    from data import common
  File "/content/gdrive/My Drive/RCAN/RCAN_TestCode/code/data/common.py", line 9, in <module>
    from torchvision import transforms
  File "/usr/local/lib/python3.6/dist-packages/torchvision/__init__.py", line 3, in <module>
    from torchvision import models
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/faster_rcnn.py", line 13, in <module>
    from .rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/rpn.py", line 8, in <module>
    from . import _utils as det_utils
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/_utils.py", line 74, in <module>
    @torch.jit.script
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 364, in script
    graph = _script_graph(fn, _frames_up=_frames_up + 1)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 359, in _script_graph
    ast = get_jit_ast(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 132, in get_jit_ast
    return build_def(SourceRangeFactory(source), py_ast.body[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 151, in build_def
    build_stmts(ctx, body))
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 123, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 123, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 205, in build_Assign
    rhs = build_expr(ctx, stmt.value)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 314, in build_Call
    func = build_expr(ctx, expr.func)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 300, in build_Attribute
    value = build_expr(ctx, expr.value)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 422, in build_Subscript
    raise NotSupportedError(base.range(), "slicing multiple dimensions at the same time isn't supported yet")
torch.jit.frontend.NotSupportedError: slicing multiple dimensions at the same time isn't supported yet
        proposals (Tensor): boxes to be encoded
    """

    # perform some unpacking to make it JIT-fusion friendly
    wx = weights[0]
    wy = weights[1]
    ww = weights[2]
    wh = weights[3]

    proposals_x1 = proposals[:, 0].unsqueeze(1)
                   ~~~~~~~~~ <--- HERE
    proposals_y1 = proposals[:, 1].unsqueeze(1)
    proposals_x2 = proposals[:, 2].unsqueeze(1)
    proposals_y2 = proposals[:, 3].unsqueeze(1)

    reference_boxes_x1 = reference_boxes[:, 0].unsqueeze(1)
    reference_boxes_y1 = reference_boxes[:, 1].unsqueeze(1)
    reference_boxes_x2 = reference_boxes[:, 2].unsqueeze(1)
    reference_boxes_y2 = reference_boxes[:, 3].unsqueeze(1)

**Comment by ZamSul** [comment]
Now I do not understand what is being referred by these reference boxes.

**Comment by XuZikang** [comment]
@greatwallet You can refer to EDSR code, git its datloader.py and replace _DataLoaderIter in it with _BaseLoaderIter.

**Comment by abhijay09** [comment]
> ImportError: cannot import name '_update_worker_pids'

Try this: https://github.com/daitao/SAN/issues/37#issuecomment-855207560
